# -*- coding: utf-8 -*-
"""Bedrock_NLP to SQL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AiplvpWqoip81sJs_4bioPHzm-By5W1d

NLP to SQL Using AWS and LangChain
"""

!pip install langchain sqlalchemy  boto3 langchain-community  langchain-experimental langchain-aws

!pip install PyMySQL

#import psycopg2
import pymysql
import sys
import boto3
from botocore.exceptions import ClientError
from langchain_community.llms import Bedrock
import os

# Database connection details
#ENDPOINT="mysqlforlambda.choy6a20ue6n.us-east-2.rds.amazonaws.com"  # Replace with your RDS endpoint
#ENDPOINT = "proxy-1757427736693-mysqlforlambda.proxy-choy6a20ue6n.us-east-2.rds.amazonaws.com"
ENDPOINT = "sofvie-database.cpockqs2w1go.us-east-2.rds.amazonaws.com"
PORT="3306" # Default MySQL port
USER="admin"  # Replace with your username
REGION="us-east-2"
#DBNAME="ExampleDB"
PASSWORD="Password#1234"  # Replace with your password
os.environ['LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN'] = '1'
# You need to set AWS_ACCESS_KEY_ID and AWS_SECRET_KEY environment variables
AWS_ACCESS_KEY_ID = "AKIAU62YVIHQS3JGOGOK"
AWS_SECRET_ACCESS_KEY = "izEUxxBjuKuZgoIrexUr7escwMqYRLYcwd"
AWS_ACCESS_KEY_ID_ASCENDION = "AKIARWPFIEOBYTBYQTFQ"
BEDROCK_API_KEY =  "ABSKQmVkcm9ja0FQSUtleS1wY2RxLWF0LTExNjk4MTc2OTA5MTpsNWtHNEVRNlp4YjcyR1dIR0g0R0kvaERtKzRGbHZYb053WStvM1FTTTgxUzZxTWErRDNmVHA3YWYrYz0="
os.environ["AWS_ACCESS_KEY_ID"] = AWS_ACCESS_KEY_ID
os.environ["AWS_SECRET_ACCESS_KEY"] = AWS_SECRET_ACCESS_KEY
os.environ["REGION"] = REGION
os.environ["BEDROCK_API_KEY"] = BEDROCK_API_KEY

# 1. Connect to RDS using boto3 to list Aurora clusters
rds_client = boto3.client(
    'rds',
    aws_access_key_id=AWS_ACCESS_KEY_ID,
    aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
    region_name=REGION
)

# For MySQL-compatible Aurora
conn = pymysql.connect(
    host=ENDPOINT,
    user=USER,
    password=PASSWORD,
    port=3306  # default MySQL port
)

# Configuration for the Aurora MySQL instance
config = {
    'user': USER,
    'password': PASSWORD,
    'host': ENDPOINT,  # Replace with your Aurora endpoint
    'database': 'technica_anonymous_2025121'
}

# Connect to the database
conn = pymysql.connect(**config)
cursor = conn.cursor()

from langchain_community.utilities import SQLDatabase
# Connect to Amazon RDS Aurora (MySQL-compatible)
db = SQLDatabase.from_uri(f"mysql+pymysql://{USER}:{PASSWORD}@{ENDPOINT}/{config['database']}")

cursor.execute("SHOW TABLES")

from langchain_core.prompts import ChatPromptTemplate
from langchain_community.tools.sql_database.tool import QuerySQLDatabaseTool
from langchain_experimental.sql import SQLDatabaseChain
from langchain_community.llms import Bedrock

def create_bedrock_client(api_key: str, region: str ):
    """
    Create an Amazon Bedrock client using a short-term API key.

    :param api_key: Short-term API key string (valid for ~30 days).
    :param region: AWS region where Bedrock is available.
    :return: boto3 Bedrock client object.
    """
    if not api_key or not isinstance(api_key, str):
        raise ValueError("A valid API key string must be provided.")

    # Configure boto3 to use the API key
    config = Config(
        region_name=region,
        retries={"max_attempts": 3, "mode": "standard"}
    )

    # Create the client with API key authentication
    client = boto3.client(
        service_name="bedrock-runtime",
        region_name=REGION,
        aws_access_key_id=AWS_ACCESS_KEY_ID_ASCENDION,  # Placeholder, required by boto3
        aws_secret_access_key=BEDROCK_API_KEY,  # API key goes here
        config=config
    )
    return client

# Create the client with standard AWS credentials
    br_client = boto3.client(
        service_name="bedrock-runtime",
        region_name=REGION,
        aws_access_key_id=AWS_ACCESS_KEY_ID,  # Use the standard AWS_ACCESS_KEY_ID
        aws_secret_access_key=AWS_SECRET_ACCESS_KEY  # Use the standard AWS_SECRET_ACCESS_KEY
    )

def invoke_model(client, model_id: str, prompt: str):
    """
    Invoke a Bedrock model with a given prompt.

    :param client: Bedrock boto3 client.
    :param model_id: Model identifier (e.g., "anthropic.claude-v2").
    :param prompt: Input text prompt.
    :return: Model output text.
    """
    try:
        response = client.invoke_model(
            modelId=model_id,
            body=prompt.encode("utf-8"),
            contentType="text/plain",
            accept="text/plain"
        )
        return response["body"].read().decode("utf-8")
    except (BotoCoreError, ClientError) as e:
        print(f"Error invoking model: {e}")
        return None

# Load API key from environment variable for security
API_KEY = BEDROCK_API_KEY
#REGION = "us-east-1"  # Change if needed
MODEL_ID = "anthropic.claude-v2"  # Example model

from botocore.exceptions import BotoCoreError, NoCredentialsError, ClientError # Added to address NameErrors and ensure all relevant exceptions are handled

try:
        #bedrock_client = create_bedrock_client(API_KEY, REGION)
        output = invoke_model(br_client, MODEL_ID, "Hello, Bedrock!")
        if output:
            print("Model output:", output)
except (ValueError, BotoCoreError, NoCredentialsError, ClientError) as e: # Updated to catch the relevant exceptions
        print(f"Setup error: {e}")

import json
response = client.invoke_model(
    modelId=model_id,            # The Bedrock model you want to use
    contentType='application/json',  # Input content type
    accept='application/json',      # Output content type
    body=json.dumps({
        "inputText": prompt
    })
)

# Parse the response
result = json.loads(response['body'])
print(result.get('outputText', 'No output returned'))

# Initialize Bedrock LLM


llm = Bedrock(
    model_id="anthropic.claude-v2",  # Example model
    region_name=os.getenv("REGION"),
    api_key=os.getenv("BEDROCK_API_KEY"))



# --- Prompt Template for NLP → SQL ---
prompt = PromptTemplate(
    input_variables=["question", "schema"],
    template="""
You are an expert SQL generator.
Given the database schema:
{schema}

Convert the following natural language request into a valid MySQL query:
{question}

Only return the SQL query, no explanations.
"""
)

chain = LLMChain(llm=llm, prompt=prompt)

# --- Example Schema ---
# Get database schema information
table_info = db.get_table_info()
   # Escape curly braces in table_info content so they don't interfere with prompt templating
escaped_table_info = table_info.replace('{', '{{').replace('}', '}}')
schema_description = escaped_table_info

# --- Convert NLP to SQL ---
nlp_question = "Show me the top 5 customers by total order amount in 2024"
sql_query = chain.run(question=nlp_question, schema=schema_description).strip()

print("Generated SQL:", sql_query)

# --- Connect to AWS RDS MySQL ---
try:
    with connection.cursor() as cursor:
        cursor.execute(sql_query)
        results = cursor.fetchall()
        print("Query Results:", results)

except pymysql.MySQLError as e:
    print("Database error:", e)

from langchain_experimental.sql import SQLDatabaseChain
from langchain_community.tools.sql_database.tool import QuerySQLDatabaseTool

# --- Convert NLP to SQL using SQLDatabaseChain ---
# SQLDatabaseChain will return the SQL query directly, or the result if return_intermediate_steps is True.
# For now, we want just the SQL, so we'll let it generate the SQL and then manually execute.

# Initialize SQLDatabaseChain
db_chain = SQLDatabaseChain.from_llm(llm=llm, db=db, verbose=True)

nlp_question = "Show me the total number of tables"

# Run the chain to get the SQL query (SQLDatabaseChain will generate and execute by default).
# To only get the SQL, we need to adapt. A common pattern is to make the LLM respond only with SQL.
# For simplicity, let's assume db_chain.run() can return SQL, or we configure it.
# Given the user's previous prompt, they want just the SQL. Let's make SQLDatabaseChain do that.

# Using QuerySQLDatabaseTool to explicitly get a SQL query from the LLM
query_tool = QuerySQLDatabaseTool(db=db)

# The LLM will generate the SQL query based on the question and schema
# We'll use a simple prompt to ensure it only returns the SQL
from langchain_core.prompts import ChatPromptTemplate

sql_query_generator_prompt = ChatPromptTemplate.from_messages([
    ("system", f"You are an expert SQL generator. Given the database schema:\n{db.get_table_info()}\nConvert the following natural language request into a valid MySQL query. Only return the SQL query, no explanations."),
    ("human", "{question}")
])

sql_generator_chain = sql_query_generator_prompt | llm # This uses the standard runnable interface

# Now, let the LLM generate the SQL query
sql_query = sql_generator_chain.invoke({"question": nlp_question}).content.strip()

print("Generated SQL:", sql_query)

# --- Connect to AWS RDS MySQL and execute --- (Keeping the original execution logic)
try:
    # Re-establish connection just in case (or ensure 'conn' is still valid from earlier cells)
    # It's safer to use the 'conn' object created earlier if it's still active
    # If 'conn' from previous cells is still valid, this reconnect is redundant but harmless.
    # If it's closed or timed out, it will re-open.
    # config was defined in Pqa2l0UK0JNU
    if not conn.open: # Check if the connection is still open
        conn = pymysql.connect(**config)
    cursor = conn.cursor()

    cursor.execute(sql_query)
    results = cursor.fetchall()
    print("Query Results:", results)

except pymysql.MySQLError as e:
    print("Database error:", e)
finally:
    # Ensure cursor and connection are closed if they were opened here
    if 'cursor' in locals() and cursor is not None:
        cursor.close()
    if 'conn' in locals() and conn is not None and conn.open:
        conn.close()

question= "how many tables are in the database"
result = nlp_to_sqlv1(question)
print(result)

question= "list  the tables and their fields related to incidents "
result = nlp_to_sql(question)
print(result)

question = " Give me a list of top ten users that have been assigned to the most hazard actions"
result = nlp_to_sql(question)
print(result)

question = "top ten incidents in 2024"
result = nlp_to_sql(question)
print(result)

import ast
import datetime # Import datetime module

# Ensure result is a Python object, not a string representation
processed_result = None
if isinstance(result, str):
    try:
        # Use eval() in a restricted environment to safely evaluate the string
        # providing access to the datetime module
        processed_result = eval(result, {'datetime': datetime, '__builtins__': {}})
    except (NameError, SyntaxError, TypeError) as e:
        print(f"Error evaluating string with datetime: {e}")
        processed_result = result # Fallback to original string if evaluation fails
else:
    processed_result = result

if processed_result and isinstance(processed_result, list):
    print("Elements from result:")
    for item in processed_result:
        if isinstance(item, tuple):
            for element in item:
                print(element)
        else:
            print(item)
elif processed_result is not None:
    print(f"Result is not a list or could not be fully parsed: {processed_result}")
else:
    print("No results to process.")

"""# Task
Modify the code in cell `Sn3LG_X5M2yc` to correctly parse the `result` string, which contains `datetime.date` and `datetime.datetime` objects, into a Python list of tuples, and then iterate through and print each element.

## Correctly parse and print elements

### Subtask:
Modify the code in cell `Sn3LG_X5M2yc` to preprocess the `result` string, specifically handling `datetime` objects, so that it can be successfully evaluated into a Python list of tuples, and then iterate through and print its elements.

## Summary:

### Data Analysis Key Findings
- The primary challenge identified in the task is the parsing of a `result` string that includes representations of `datetime.date` and `datetime.datetime` objects.
- The goal is to successfully convert this string into a standard Python list of tuples.
- After conversion, each element within the list of tuples needs to be iterated through and printed.

### Insights or Next Steps
- Accurate parsing of `datetime` objects from string representations is critical for ensuring data integrity and enabling subsequent time-series analysis or date-based operations.
- Upon successful conversion to a Python list of tuples, the next step would typically involve further data processing, filtering, or analysis based on the specific content and purpose of the data.
"""