# -*- coding: utf-8 -*-
"""NLP to SQL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F29BGLzbyAS5_n2CQWzhOIF4pJhLypmF

NLP to SQL Using AWS and LangChain
"""

!pip install langchain sqlalchemy psycopg2 boto3 langchain-community langchain-openai

# !pip install pymysql
!pip  install PyMySQL

#import psycopg2
import pymysql
import sys
import boto3
from botocore.exceptions import ClientError
import os

# Database connection details
#ENDPOINT="mysqlforlambda.choy6a20ue6n.us-east-2.rds.amazonaws.com"  # Replace with your RDS endpoint
#ENDPOINT = "proxy-1757427736693-mysqlforlambda.proxy-choy6a20ue6n.us-east-2.rds.amazonaws.com"
ENDPOINT = "sofvie-database.cpockqs2w1go.us-east-2.rds.amazonaws.com"
PORT="3306" # Default MySQL port
USER="admin"  # Replace with your username
REGION="us-east-2"
#DBNAME="ExampleDB"
PASSWORD="Password#1234"  # Replace with your password
os.environ['LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN'] = '1'
# You need to set AWS_ACCESS_KEY_ID and AWS_SECRET_KEY environment variables
AWS_ACCESS_KEY_ID = "AKIAU62YVIHQS3JGOGOK"
AWS_SECRET_ACCESS_KEY = "izEUxxBjuKuZgoIrexUr7escwMqYRLYcwd"

# 1. Connect to RDS using boto3 to list Aurora clusters
rds_client = boto3.client(
    'rds',
    aws_access_key_id=AWS_ACCESS_KEY_ID,
    aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
    region_name=REGION
)

# For MySQL-compatible Aurora
conn = pymysql.connect(
    host=ENDPOINT,
    user=USER,
    password=PASSWORD,
    port=3306  # default MySQL port
)

# Configuration for the Aurora MySQL instance
config = {
    'user': USER,
    'password': PASSWORD,
    'host': ENDPOINT,  # Replace with your Aurora endpoint
    'database': 'technica_anonymous_2025121'
}

# Connect to the database
conn = pymysql.connect(**config)
cursor = conn.cursor()

from langchain_community.utilities import SQLDatabase
# Connect to Amazon RDS Aurora (MySQL-compatible)
db = SQLDatabase.from_uri(f"mysql+pymysql://{USER}:{PASSWORD}@{ENDPOINT}/{config['database']}")

from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_community.tools.sql_database.tool import QuerySQLDatabaseTool

import os
# Set your OpenAI API key as an environment variable
# IMPORTANT: Replace 'YOUR_OPENAI_API_KEY' with your actual OpenAI API key
os.environ["OPENAI_API_KEY"] = "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"

llm = ChatOpenAI(model="gpt-5.2", temperature=0, max_tokens=500)

from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_community.tools.sql_database.tool import QuerySQLDatabaseTool
# Initialize LLM (e.g., OpenAI GPT)
llm = ChatOpenAI(model="gpt-5.2", temperature=0)

# Define the chain
def nlp_to_sql(question):
   # Get database schema information
   table_info = db.get_table_info()
   # Escape curly braces in table_info content so they don't interfere with prompt templating
   escaped_table_info = table_info.replace('{', '{{').replace('}', '}}')

   # Define the prompt for SQL generation, including the schema
   system_message = f"""
   You are an expert in SQL. Your task is to generate a syntactically correct SQL query based on the user's question and the provided database schema.
   **ONLY output the SQL query and nothing else.**

   Database Schema:
   {escaped_table_info}

   Given the input question, create a syntactically correct SQL query.
   Use only the tables and columns provided in the schema.
   Limit results to {{top_k}} rows unless specified otherwise.
   """
   query_prompt = ChatPromptTemplate.from_messages([("system", system_message)])

   # Generate SQL query
   sql_query_message = llm.invoke(query_prompt.format(input=question, top_k=10))
   # Extract the content (SQL query string) from the AIMessage object
   sql_query_string = sql_query_message.content

   # Execute query on database
   query_tool = QuerySQLDatabaseTool(db=db)
   result = query_tool.invoke(sql_query_string)
   return result

question = "how many tables are in the database"
result = nlp_to_sql(question)
print(result)