# -*- coding: utf-8 -*-
"""OpenAI_NLP to SQL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1micLsuNQOVa7OXRwId1uWC0m1Ramnza4

NLP to SQL Using AWS and LangChain
"""

!pip install langchain sqlalchemy  boto3 langchain-community langchain-openai

!pip install PyMySQL langchain-experimental

#import psycopg2
import pymysql
import sys
import boto3
from botocore.exceptions import ClientError
import os

# Database connection details
#ENDPOINT="mysqlforlambda.choy6a20ue6n.us-east-2.rds.amazonaws.com"  # Replace with your RDS endpoint
#ENDPOINT = "proxy-1757427736693-mysqlforlambda.proxy-choy6a20ue6n.us-east-2.rds.amazonaws.com"
ENDPOINT = "sofvie-database.cpockqs2w1go.us-east-2.rds.amazonaws.com"
PORT="3306" # Default MySQL port
USER="admin"  # Replace with your username
REGION="us-east-2"
#DBNAME="ExampleDB"
PASSWORD="Password#1234"  # Replace with your password
os.environ['LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN'] = '1'
# You need to set AWS_ACCESS_KEY_ID and AWS_SECRET_KEY environment variables
AWS_ACCESS_KEY_ID = "AKIAU62YVIHQS3JGOGOK"
AWS_SECRET_ACCESS_KEY = "izEUxxBjuKuZgoIrexUr7escwMqYRLYcwd"

# 1. Connect to RDS using boto3 to list Aurora clusters
rds_client = boto3.client(
    'rds',
    aws_access_key_id=AWS_ACCESS_KEY_ID,
    aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
    region_name=REGION
)

# For MySQL-compatible Aurora
conn = pymysql.connect(
    host=ENDPOINT,
    user=USER,
    password=PASSWORD,
    port=3306  # default MySQL port
)

# Configuration for the Aurora MySQL instance
config = {
    'user': USER,
    'password': PASSWORD,
    'host': ENDPOINT,  # Replace with your Aurora endpoint
    'database': 'technica_anonymous_2025121'
}

# Connect to the database
conn = pymysql.connect(**config)
cursor = conn.cursor()

from langchain_community.utilities import SQLDatabase
# Connect to Amazon RDS Aurora (MySQL-compatible)
db = SQLDatabase.from_uri(f"mysql+pymysql://{USER}:{PASSWORD}@{ENDPOINT}/{config['database']}")

from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_community.tools.sql_database.tool import QuerySQLDatabaseTool
from langchain_experimental.sql import SQLDatabaseChain

import os
from google.colab import userdata
# Set your OpenAI API key as an environment variable
# IMPORTANT: Replace 'YOUR_OPENAI_API_KEY' with your actual OpenAI API key
os.environ["OPENAI_API_KEY"] = "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"
# os.environ["OPENAI_API_KEY"] = userdata.get('OPENAI_API_KEY')
llm = ChatOpenAI(model="gpt-5.2", temperature=0, max_tokens=2000)

# Create the SQL-to-NLP chain
db_chain = SQLDatabaseChain.from_llm(llm, db, verbose=True)

# Define the chain
def nlp_to_sql(question):
   # Get database schema information
   #table_info = db.get_table_info()

   # Get schema info for specific tables
   table_info=db.get_table_info(["SubmissionHAP", "SubmissionHeader","SubmissionDetails","SubmissionDetails_Explode","lineup_distribution","submission_hazard_action_completed_person","submission_general_action_person"])

   # Escape curly braces in table_info content so they don't interfere with prompt templating
   escaped_table_info = table_info.replace('{', '{{').replace('}', '}}')

   # Define the prompt for SQL generation, including the schema
   system_message = f"""
   You are an expert in SQL. Your task is to generate a syntactically correct SQL query based on the user's question and the provided database schema.
   **ONLY output the SQL query and nothing else.**

   Database Schema:
   {escaped_table_info}

   Given the input question, create a syntactically correct SQL query.
   Use only the tables and columns provided in the schema.

   Limit results to {{top_k}} rows unless specified otherwise.
   """
   query_prompt = ChatPromptTemplate.from_messages([("system", system_message)])
   # Generate SQL query using LLM
   sql_query_message = llm.invoke(query_prompt.format(input=question, top_k=10))
   # Extract the content (SQL query string) from the AIMessage object
   sql_query_string = sql_query_message.content
   print(f"Generated SQL Query: {sql_query_string}")
   # Execute query on database
   query_tool = QuerySQLDatabaseTool(db=db)
   result = query_tool.invoke(sql_query_string)
   return result

def nlp_to_sqlv1(question):
   # Get database schema information
   table_info = db.get_table_info()
   # Escape curly braces in table_info content so they don't interfere with prompt templating
   escaped_table_info = table_info.replace('{', '{{').replace('}', '}}')

   # Define the prompt for SQL generation, including the schema
   system_message = f"""
   You are an expert in SQL. Your task is to generate a syntactically correct SQL query based on the user's question and the provided database schema.
   **ONLY output the SQL query and nothing else.**

   Database Schema:
   {escaped_table_info}

   Given the input question, create a syntactically correct SQL query.
   Use only the tables and columns provided in the schema.
   Limit results to {{top_k}} rows unless specified otherwise.
   """
   query_prompt = ChatPromptTemplate.from_messages([("system", system_message)])

   # Generate SQL query
   sql_query_message = llm.invoke(query_prompt.format(input=question, top_k=10))
   # Extract the content (SQL query string) from the AIMessage object
   sql_query_string = sql_query_message.content
   print(f"Generated SQL Query: {sql_query_string}")
   # Execute query on database
   query_tool = QuerySQLDatabaseTool(db=db)
   result = query_tool.invoke(sql_query_string)
   return result

# Get database schema information
   print(db.get_table_info(["SubmissionHAP", "SubmissionHeader","SubmissionDetails","SubmissionDetails_Explode","lineup_distribution","submission_hazard_action_completed_person","submission_general_action_person"]))

question = " Give me a list of top ten users that have been assigned to the most hazard actions"
result = nlp_to_sql(question)
print(result)

question = " Give me a list of  the most hazard actions"
result = nlp_to_sql(question)
print(result)

import ast
import datetime # Import datetime module

# Ensure result is a Python object, not a string representation
processed_result = None
if isinstance(result, str):
    try:
        # Use eval() in a restricted environment to safely evaluate the string
        # providing access to the datetime module
        processed_result = eval(result, {'datetime': datetime, '__builtins__': {}})
    except (NameError, SyntaxError, TypeError) as e:
        print(f"Error evaluating string with datetime: {e}")
        processed_result = result # Fallback to original string if evaluation fails
else:
    processed_result = result

if processed_result and isinstance(processed_result, list):
    print("Elements from result:")
    for item in processed_result:
        if isinstance(item, tuple):
            for element in item:
                print(element)
        else:
            print(item)
elif processed_result is not None:
    print(f"Result is not a list or could not be fully parsed: {processed_result}")
else:
    print("No results to process.")