# -*- coding: utf-8 -*-
"""Sofvie_RDS_Connection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XmEE7Mk6RJQST1P4N3_cWWOaEC9nb-SB
"""

# !pip install pymysql
!pip  install PyMySQL

!pip install boto3

#import psycopg2
import pymysql
import sys
import boto3
from botocore.exceptions import ClientError
import os

# Database connection details
#ENDPOINT="mysqlforlambda.choy6a20ue6n.us-east-2.rds.amazonaws.com"  # Replace with your RDS endpoint
#ENDPOINT = "proxy-1757427736693-mysqlforlambda.proxy-choy6a20ue6n.us-east-2.rds.amazonaws.com"
ENDPOINT = "sofvie-database.cpockqs2w1go.us-east-2.rds.amazonaws.com"
PORT="3306" # Default MySQL port
USER="admin"  # Replace with your username
REGION="us-east-2"
#DBNAME="ExampleDB"
PASSWORD="Password#1234"  # Replace with your password
os.environ['LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN'] = '1'
# You need to set AWS_ACCESS_KEY_ID and AWS_SECRET_KEY environment variables
AWS_ACCESS_KEY_ID = "AKIAU62YVIHQS3JGOGOK"
AWS_SECRET_ACCESS_KEY = "izEUxxBjuKuZgoIrexUr7escwMqYRLYcwd"

# 1. Connect to RDS using boto3 to list Aurora clusters
rds_client = boto3.client(
    'rds',
    aws_access_key_id=AWS_ACCESS_KEY_ID,
    aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
    region_name=REGION
)

# For MySQL-compatible Aurora
conn = pymysql.connect(
    host=ENDPOINT,
    user=USER,
    password=PASSWORD,
    port=3306  # default MySQL port
)

with conn.cursor() as cursor:
    cursor.execute("SHOW DATABASES;")
    databases = cursor.fetchall()
    print("Databases in the Aurora cluster:")
    for db in databases:
        print(db[0])

conn.close()

# Configuration for the Aurora MySQL instance
config = {
    'user': USER,
    'password': PASSWORD,
    'host': ENDPOINT,  # Replace with your Aurora endpoint
    'database': 'technica_anonymous_2025121'
}

# Connect to the database
conn = pymysql.connect(**config)
cursor = conn.cursor()

cursor.execute("SHOW TABLES")

schema = cursor.fetchall()

print("Tables in database:")
for table in schema:
    print(f"- {table[0]}")

# Function to show schema for a given table
def show_table_schema(table_name):
    cursor.execute(f"DESCRIBE {table_name}")
    schema = cursor.fetchall()
    print(f"Schema for table '{table_name}':")
    print(f"{'Field':<20}{'Type':<20}{'Null':<10}{'Key':<10}{'Default':<15}{'Extra'}")
    for col in schema:
        print(f"{col[0]:<20}{col[1]:<20}{col[2]:<10}{col[3]:<10}{str(col[4]):<15}{col[5]}")

show_table_schema("preop_submission_value")

show_table_schema("custom_form_detail_value")

show_table_schema("SubmissionDetails_Explode")

def count_records_in_table(table_name):
    try:
        # Ensure the table name is properly quoted to prevent SQL injection and handle special characters
        # In MySQL, backticks (`) are used to quote identifiers.
        query = f"SELECT COUNT(*) FROM `{table_name}`"
        cursor.execute(query)
        count = cursor.fetchone()[0]
        return count
    except pymysql.Error as e:
        print(f"Error counting records in table {table_name}: {e}")
        return None

i=0
total_records = 0
print("Record counts for each table:")
for table_tuple in schema:
    table_name = table_tuple[0]
    count = count_records_in_table(table_name)
    if count > 0:
        print(f"- Table '{table_name}': {count} records")
        i=i+1
        total_records += count
print(f"Total tables with data: {i}")
print(f"Total records in all tables: {total_records}")

count_records_in_table("SubmissionDetails_Explode")

count_records_in_table("preop_submission_value")

count_records_in_table("custom_form_detail_value")

query= """SELECT
  i.ID,
  i.IncidentNumber,
  i.inc_minimum_incident_date,
  i.CreationDate
FROM Incidents i
ORDER BY i.CreationDate DESC
LIMIT 10;"""

cursor.execute(query)
results = cursor.fetchall()

print("Latest 10 Incidents:")
for row in results:
    print(row)



query= """SELECT
  i.ID,
  i.IncidentNumber,
  i.inc_minimum_incident_date,
  i.CreationDate,
  i.CreatedBy
FROM Incidents i
ORDER BY i.CreationDate   DESC
LIMIT 10;"""

cursor.execute(query)
results = cursor.fetchall()

print("Latest 10 Incidents:")
for row in results:
    print(row)

type(results)

